services: 
  
  image_processing:
    image: ${DOCKER_IMAGE_NAME}
    # volumes:
    #   - ${BIND_MOUNT_PATH}:/app/images
    ports:
      - 8000:8000
    container_name: yolo_server
    environment:
      - IMAGE_URL=${LOCALHOST_PICTURE_PATH}
      